// ─── Markdown data ─────────────────────────────────────────────────────────────
export const CRICKET_DATA = {
  problem: "Who is the king of cricket?",
  solution_1: `The title **"King of Cricket"** is often subjectively given to legendary players based on their dominance, records, and impact on the game. Here are the most common contenders:\n\n### 1. Sachin Tendulkar (India)\n- **Why?** The "God of Cricket" holds numerous records, including most runs in **Tests (15,921) & ODIs (18,426)**, and **100 international centuries**.\n- **Era:** 1989–2013\n- **Legacy:** Unmatched consistency across formats for **24 years**.\n\n### 2. Sir Don Bradman (Australia)\n- **Why?** The greatest **Test batsman ever** with a **career average of 99.94** (unmatched).\n- **Era:** 1928–1948\n- **Legacy:** His records (e.g., 6996 runs in 52 Tests) still stand after **80+ years**.\n\n### 3. Virat Kohli (India)\n- **Why?** The **"Chase Master"** with **80+ international centuries**, most ODI centuries (50), and dominance in all formats.\n- **Era:** 2008–Present\n- **Legacy:** Modern-day great with unmatched fitness and aggression.\n\n### 4. Sir Vivian Richards (West Indies)\n- **Why?** The most **dominant batsman of the 1970s–80s**, feared for his aggressive style.\n- **Era:** 1974–1991\n- **Legacy:** Strike rate was revolutionary for his time.\n\n### 5. Brian Lara (West Indies)\n- **Why?** Holds the **highest individual Test score (400*)** and carried West Indies batting for over a decade.\n- **Era:** 1990–2007\n\n**Final Verdict:** There's no official "King," but **Sachin Tendulkar** and **Don Bradman** are the most universally respected. **Kohli** is the current fan-favourite.`,
  solution_2: `The title "King of Cricket" is often associated with **Don Bradman**, the legendary Australian cricketer. Bradman, who played from 1928 to 1948, is widely regarded as the greatest batsman in the history of the sport. His career batting average of **99.94** is considered one of the most extraordinary achievements in cricket and remains unmatched.\n\nIn modern times, **Sachin Tendulkar** from India is also often referred to as the "King of Cricket" due to his immense contributions to the sport, his records, and his global popularity. Tendulkar holds the record for the most runs and centuries in both Test and One Day International (ODI) cricket.\n\nBoth Bradman and Tendulkar are iconic figures in cricket, and the title "King of Cricket" is often used to honour their unparalleled contributions to the game.`,
  judge: {
    solution_1_score: 6,
    solution_2_score: 8,
    solution_1_reasoning: "Solution 1 provides a very comprehensive list of players often associated with the title and correctly identifies the modern context where Virat Kohli is specifically nicknamed 'King'. However, it contains some factual inaccuracies in its legacy sections that detract from reliability.",
    solution_2_reasoning: "Solution 2 is factually accurate and identifies the two most iconic figures generally cited in the all-time debate (Bradman and Tendulkar). It correctly cites Bradman's average of 99.94. However, it misses the modern cultural nuance — Virat Kohli is most commonly called 'The King' today."
  }
};

export const GENERIC_TEMPLATES = {
  science: {
    solution_1: `**From a scientific standpoint**, this is a fascinating question debated by researchers for decades.\n\n### Key Perspectives\n- **Classical View** — Traditional science suggests the answer involves fundamental principles dating back to Newton and Einstein.\n- **Modern Research** — Recent studies from leading institutions have expanded our understanding significantly.\n- **Quantum Mechanics** — At the subatomic level, the answer becomes even more nuanced and counterintuitive.\n\n### Current Consensus\n- Most scientists agree on the **core principles** but debate the finer details.\n- Emerging fields like **quantum computing** and **AI** are reshaping what we know.\n\n**Bottom line:** The scientific community leans toward a multi-faceted answer that depends heavily on context and scale of observation.`,
    solution_2: `The answer revolves around **empirical evidence** gathered over centuries of scientific inquiry.\n\n**Core Findings:**\n- Multiple peer-reviewed studies confirm the primary hypothesis.\n- The evidence strongly supports a deterministic worldview at macroscopic scales.\n- However, statistical mechanics introduces probabilistic elements at smaller scales.\n\n**Practical Implications:**\nUnderstanding this helps us build better technologies and make more accurate predictions about the natural world.\n\n**Conclusion:** Science provides a clear framework, though the full picture continues to evolve as new discoveries are made.`,
    judge: { solution_1_score: 7, solution_2_score: 8, solution_1_reasoning: "Comprehensive but slightly verbose. Covers multiple perspectives well and explains the nuance effectively.", solution_2_reasoning: "Clear, evidence-based, and well-structured. Minor gaps in covering emerging research but overall very solid." }
  },
  tech: {
    solution_1: `**Technically speaking**, this is one of the most hotly debated topics in the software engineering community.\n\n### The Case FOR\n- **Performance:** Benchmarks consistently show superior throughput in controlled environments.\n- **Developer Experience:** High-quality tooling, extensive documentation, and large communities.\n- **Scalability:** Proven at hyperscale by companies like Google, Meta, and Netflix.\n\n### The Case AGAINST\n- **Learning Curve:** Steep initial investment required for mastery.\n- **Overhead:** Can be overkill for small projects.\n\n**Use it when:** You need reliability, performance, and team consensus.`,
    solution_2: `From a **pragmatic engineering perspective**, the answer depends entirely on your use case.\n\n### Key Considerations\n1. **Team Expertise** — Choose what your team knows best. Productivity beats theoretical superiority.\n2. **Project Scale** — A simple CRUD app vs. a distributed system require very different tools.\n3. **Ecosystem** — Consider available libraries, frameworks, and community support.\n\n**My Recommendation:**\n- For **startups**: Optimize for speed of development.\n- For **enterprises**: Optimize for maintainability and scale.\n\n**Conclusion:** There is no universal "best." Context is king.`,
    judge: { solution_1_score: 7, solution_2_score: 9, solution_1_reasoning: "Strong technical depth but slightly opinionated without providing full context for the reader to decide.", solution_2_reasoning: "Excellent balance of pragmatism and nuance. Highly applicable and actionable advice for any developer." }
  },
  default: {
    solution_1: `This is an excellent question that deserves a thorough analysis.\n\n### Overview\nThere are multiple ways to approach this question, each offering unique insights and perspectives.\n\n### Key Points\n- **Historical Context** — Looking at how this topic evolved over time gives important baseline knowledge.\n- **Current State** — Today, the landscape is significantly different from what it was a decade ago.\n- **Future Outlook** — Trends suggest continued evolution in surprising directions.\n\n### Analysis\nThe most common answer tends to oversimplify the matter. A deeper dive reveals layers of complexity most casual observers miss. Expert consensus, while not unanimous, points in a clear general direction.\n\n**My take:** Browse multiple credible sources and form your own informed opinion.`,
    solution_2: `A direct answer requires considering **three main angles**:\n\n**1. The Factual Angle**\nThe measurable, verifiable data points are clear: established facts and widely accepted evidence support a specific conclusion.\n\n**2. The Subjective Angle**\nPersonal preference, cultural background, and individual goals all play a significant role in what makes the "right" answer.\n\n**3. The Contextual Angle**\nContext overrides almost everything. The "best" answer in one scenario may be the worst in another.\n\n**Putting it Together:**\nIf you had to choose one answer, the evidence-based consensus provides the strongest foundation. But nuance matters.\n\n**Recommendation:** Start with the data, layer in your context, and make an informed decision.`,
    judge: { solution_1_score: 7, solution_2_score: 8, solution_1_reasoning: "Thorough and well-rounded coverage of the topic with good structure. Good use of structured points to explain complexity.", solution_2_reasoning: "Clear and highly structured response that provides a useful decision-making framework. Slightly more actionable than Solution 1." }
  }
};

export function getDataForQuestion(question) {
  const q = question.toLowerCase();
  if (/cricket|sachin|bradman|kohli|virat|babar/.test(q)) return CRICKET_DATA;
  let category = 'default';
  if (/quantum|physics|chemistry|biology|science|atom|relativity|evolution|energy|space|gravity/.test(q)) category = 'science';
  else if (/programming|language|code|javascript|python|react|vue|angular|framework|developer|software|api|database|backend|frontend/.test(q)) category = 'tech';
  const t = GENERIC_TEMPLATES[category];
  return { problem: question, solution_1: t.solution_1, solution_2: t.solution_2, judge: t.judge };
}
